### ISSUE TITLE
Update samples to use `semanticDescription` property

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/Copilot-for-M365-Samples#100]
Update samples to use the new `semanticDescription` property

https://learn.microsoft.com/microsoftteams/platform/messaging-extensions/high-quality-message-extension?tabs=tasks#semantic-description

**Comment by IntranetFactory** [comment]
We are in the "Microsoft Copilot Developer Tenant Private Preview Program" - should it be available there?
