### ISSUE TITLE
How to deploy the application on azure is there a step-by-step guideline

### ISSUE THREAD

**Issue by rahulsnc3it** [OfficeDev/Copilot-for-M365-Samples#111]
### Sample

msgext-doc-search-csharp

### Description

Need help on deploying the application on azure..

### Steps to reproduce

Need help on deploying the application on azure..

### Expected results

Need help on deploying the application on azure..

### Actual results

Need help on deploying the application on azure..

### Additional Info

Need help on deploying the application on azure..

**Comment by garrytrinder** [comment]
@aycabas could you take a look into this?

**Comment by aycabas** [comment]
Hi @rahulsnc3it you can deploy this plugin to Azure by using Teams Toolkit for Visual Studio, please follow this doc and let me know if you have any other questions: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/deploy-vs
