### ISSUE TITLE
[Bug]: Need to implement Refresh - chokes on them now and they are appearing in some env'ts

### ISSUE THREAD

**Issue by BobGerman** [OfficeDev/Copilot-for-M365-Samples#114]
### Sample

msgext-northwind-inventory-ts

### Description

@therealjohn observed errors when placing the adaptive card
We are suddenly receiving Refresh activities. Workaround is to return status code 200 instead of 400 on line 55 of searchApp.ts.
This issue should be resolved properly and we should actually refresh the card when we get these.

### Steps to reproduce

Place a card in chat via the ordinary ME interface
You will see an error on the bottom of the card. This is due to the refresh failure.

### Expected results

Card should not show an error

### Actual results

Card shows an error

**Comment by BobGerman** [comment]
UPDATE: This PR contains the workaround: https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/pull/115
Keeping this issue open so we properly implement Refresh activity handling in the future...

@rabwill @garrytrinder

**Comment by garrytrinder** [comment]
Closing issue as #115 has been merged
