### ISSUE TITLE
declarativeCopilots, response_semantics ?

### ISSUE THREAD

**Issue by IntranetFactory** [OfficeDev/Copilot-for-M365-Samples#138]
We are trying to define a declarative copilot for our own API. We did not find any definition for the schemas of the json like  "response_semantics"   
https://github.com/OfficeDev/Copilot-for-M365-Plugins-Samples/blob/main/samples/cext-trey-research/appPackage/trey-plugin.json#L11

So we are wondering if the schemas are already documented somewhere.

**Comment by garrytrinder** [comment]
To my knowledge there is no public schema available. Please note that Declarative copilots are currently in private preview, as updates are made to the feature we will update the samples.

**Comment by BobGerman** [comment]
Try this: https://aka.ms/json-schemas/copilot-extensions/v1.0/declarative-copilot.schema.json

**Comment by IntranetFactory** [comment]
The https://aka.ms/json-schemas/copilot-extensions/v1.0/declarative-copilot.schema.json file seems to have no definition for `response_semantics`. We have dozens of existing AdaptiveCards and one endpoint returning the data for each of the cards. I'm wondering how to declare which endpoints should be used and how `response_semantics` should be defined.
